from scripts.motor_campo.modelos import Escenario, ResultadoEsperado


def obtener_escenarios_especiales() -> list[Escenario]:
    return [
        Escenario(id="nc_cliente", grupo="especiales", descripcion="NC rectificativa de FC",
                  datos_extraidos_base={"tipo": "NC", "emisor_cif": "B12345678", "receptor_cif": "A98765432",
                                        "fecha": "2025-07-01", "numero_factura": "NC-TEST-001",
                                        "base_imponible": -500.0, "iva_porcentaje": 21, "total": -605.0,
                                        "coddivisa": "EUR", "tasaconv": 1.0,
                                        "lineas": [{"descripcion": "Devolución parcial", "cantidad": 1,
                                                    "precio_unitario": -500.0, "codimpuesto": "IVA21"}]},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
        Escenario(id="nc_proveedor", grupo="especiales", descripcion="NC rectificativa de FV",
                  datos_extraidos_base={"tipo": "NC", "emisor_cif": "A11111111", "receptor_cif": "B12345678",
                                        "fecha": "2025-07-15", "numero_factura": "NC-PROV-001",
                                        "base_imponible": -300.0, "iva_porcentaje": 21, "total": -363.0,
                                        "coddivisa": "EUR", "tasaconv": 1.0,
                                        "lineas": [{"descripcion": "Devolución", "cantidad": 1,
                                                    "precio_unitario": -300.0, "codimpuesto": "IVA21"}]},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
        Escenario(id="nom_basica", grupo="especiales", descripcion="Nómina con IRPF y SS",
                  datos_extraidos_base={"tipo": "NOM", "emisor_cif": "B12345678",
                                        "fecha": "2025-06-30", "numero_factura": "NOM-2025-06",
                                        "base_imponible": 2000.0, "irpf_porcentaje": 15,
                                        "ss_empresa": 600.0, "ss_trabajador": 126.0,
                                        "total": 1874.0, "coddivisa": "EUR"},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
        Escenario(id="sum_suministro", grupo="especiales", descripcion="Suministro luz/agua",
                  datos_extraidos_base={"tipo": "SUM", "emisor_nombre": "ENDESA S.A.",
                                        "emisor_cif": "A81948077",
                                        "fecha": "2025-06-15", "numero_factura": "SUM-001",
                                        "base_imponible": 150.0, "iva_porcentaje": 21, "total": 181.5,
                                        "coddivisa": "EUR",
                                        "lineas": [{"descripcion": "Consumo eléctrico", "cantidad": 1,
                                                    "precio_unitario": 150.0, "codimpuesto": "IVA21"}]},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
        Escenario(id="rlc_ss", grupo="especiales", descripcion="Recibo liquidación SS",
                  datos_extraidos_base={"tipo": "RLC", "emisor_nombre": "TESORERIA SEGURIDAD SOCIAL",
                                        "fecha": "2025-06-20", "numero_factura": "RLC-2025-06",
                                        "base_imponible": 726.0, "iva_porcentaje": 0, "total": 726.0,
                                        "coddivisa": "EUR"},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
        Escenario(id="imp_tasa", grupo="especiales", descripcion="Tasa/impuesto AAPP",
                  datos_extraidos_base={"tipo": "IMP", "emisor_nombre": "AYUNTAMIENTO TEST",
                                        "fecha": "2025-05-10", "numero_factura": "IMP-001",
                                        "base_imponible": 200.0, "iva_porcentaje": 0, "total": 200.0,
                                        "coddivisa": "EUR"},
                  resultado_esperado=ResultadoEsperado(http_status=200, debe_igual_haber=True)),
    ]
