import {
  TipoDocumento,
  Portal,
  MetodoDescarga,
  EstadoVerificacion,
  type DefinicionDocumento,
} from './tipos-documentales'

/** Catalogo completo de documentos descargables */
export const CATALOGO_DOCUMENTOS: DefinicionDocumento[] = [
  // ── AEAT ──────────────────────────────────────────────────
  {
    id: TipoDocumento.DEUDAS_AEAT,
    nombre: 'Certificado de deudas tributarias',
    descripcion: 'Certificado de estar al corriente de obligaciones tributarias con la AEAT',
    portal: Portal.AEAT,
    url: 'https://www1.agenciatributaria.gob.es/wlpl/EMCE-JDIT/ECOTInternetCiudadanosServlet',
    nombreArchivo: 'Deudas_AEAT',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: true,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.DATOS_FISCALES,
    nombre: 'Datos fiscales',
    descripcion: 'Datos fiscales del contribuyente (3 ultimos ejercicios)',
    portal: Portal.AEAT,
    url: 'https://www1.agenciatributaria.gob.es/wlpl/DFPA-D182/SvVisDFNet',
    nombreArchivo: 'Datos_Fiscales',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: true,
    multiArchivo: true,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.CERTIFICADOS_IRPF,
    nombre: 'Certificados tributarios IRPF',
    descripcion: 'Certificados tributarios del IRPF (3 ultimos ejercicios)',
    portal: Portal.AEAT,
    url: 'https://www1.agenciatributaria.gob.es/wlpl/CERE-EMCE/InternetServlet',
    nombreArchivo: 'Certificado_IRPF',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: true,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.CNAE_AUTONOMO,
    nombre: 'Informe actividades autonomo (CNAE)',
    descripcion: 'Informe de actividades del trabajador autonomo',
    portal: Portal.SEGURIDAD_SOCIAL,
    url: 'https://portal.seg-social.gob.es/wps/myportal/importass/importass/personal/',
    nombreArchivo: 'Informe_CNAE_Autonomo',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
    notaVerificacion: 'Reescrito — pendiente testear con certificado de autonomo',
  },
  {
    id: TipoDocumento.IAE_ACTIVIDADES,
    nombre: 'Actividades IAE',
    descripcion: 'Certificado tributario del Impuesto de Actividades Economicas',
    portal: Portal.AEAT,
    url: 'https://www1.agenciatributaria.gob.es/wlpl/EMCE-JDIT/ServletAaeeGralnternet',
    nombreArchivo: 'Actividades_IAE',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },

  // ── Seguridad Social ──────────────────────────────────────
  {
    id: TipoDocumento.DEUDAS_SS,
    nombre: 'Certificado de deudas con la Seguridad Social',
    descripcion: 'Certificado de estar al corriente con la Tesoreria General de la SS',
    portal: Portal.SEGURIDAD_SOCIAL,
    url: 'https://sp.seg-social.es/ProsaInternet/OnlineAccess?ARQ.SPM.ACTION=LOGIN&ARQ.SPM.APPTYPE=SERVICE&ARQ.IDAPP=AECPSED1&PAUC.NIVEL=1&PAUC.TIPO_IDENTIFICACION=2',
    nombreArchivo: 'Deudas_SS',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: true,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
    notaVerificacion: 'Reescrito Chrome MCP 2026-02-21 — pendiente testear',
  },
  {
    id: TipoDocumento.VIDA_LABORAL,
    nombre: 'Vida laboral',
    descripcion: 'Informe de vida laboral de la TGSS',
    portal: Portal.SEGURIDAD_SOCIAL,
    url: 'https://portal.seg-social.gob.es/wps/portal/importass/importass/Categorias/Vida+laboral+e+informes/Informes+sobre+tu+situacion+laboral/Informe+de+tu+vida+laboral',
    nombreArchivo: 'Vida_Laboral',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: true,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.CERTIFICADO_INSS,
    nombre: 'Certificado INSS',
    descripcion: 'Certificado integrado de prestaciones del INSS (Tu Seguridad Social)',
    portal: Portal.SEGURIDAD_SOCIAL,
    url: 'https://sede-tu.seg-social.gob.es/wps/myportal/tussR/tuss/TrabajoPensiones/Pensiones/CertificadoIntegradoPrestaciones',
    nombreArchivo: 'Certificado_INSS',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },

  // ── Carpeta Ciudadana ─────────────────────────────────────
  {
    id: TipoDocumento.CONSULTA_VEHICULOS,
    nombre: 'Consulta de vehiculos',
    descripcion: 'Consulta de vehiculos registrados (Carpeta Ciudadana + DGT)',
    portal: Portal.CARPETA_CIUDADANA,
    url: 'https://carpetaciudadana.gob.es/carpeta/datos/vehiculos/consulta.htm?idioma=es',
    nombreArchivo: 'Consulta_Vehiculos',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: true,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.CONSULTA_INMUEBLES,
    nombre: 'Consulta de inmuebles (Catastro)',
    descripcion: 'Consulta de bienes inmuebles desde el Catastro via Carpeta Ciudadana',
    portal: Portal.CARPETA_CIUDADANA,
    url: 'https://carpetaciudadana.gob.es/carpeta/mcc/bienes-inmuebles',
    nombreArchivo: 'Consulta_Inmuebles',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.EMPADRONAMIENTO,
    nombre: 'Certificado de empadronamiento',
    descripcion: 'Certificado de empadronamiento municipal via Carpeta Ciudadana',
    portal: Portal.CARPETA_CIUDADANA,
    url: 'https://carpetaciudadana.gob.es/carpeta/mcc/domicilio',
    nombreArchivo: 'Empadronamiento',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.CERTIFICADO_PENALES,
    nombre: 'Certificado de antecedentes penales',
    descripcion: 'Certificado de antecedentes penales via Carpeta Ciudadana',
    portal: Portal.CARPETA_CIUDADANA,
    url: 'https://carpetaciudadana.gob.es/carpeta/mcc/antecedentes-penales',
    nombreArchivo: 'Certificado_Penales',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
    notaVerificacion: 'Descarga AJAX (no will-download): fetch /api/antecedentes-penales/justificante → base64 → writeFileSync',
  },

  // ── Justicia ──────────────────────────────────────────────
  {
    id: TipoDocumento.CERTIFICADO_NACIMIENTO,
    nombre: 'Certificado de nacimiento',
    descripcion: 'Certificado literal de nacimiento del Ministerio de Justicia',
    portal: Portal.JUSTICIA,
    url: 'https://sede.mjusticia.gob.es/sereci/clave/solicitarCertificadoSolicitudLiteral?idMateria=NAC',
    nombreArchivo: 'Certificado_Nacimiento',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.APUD_ACTA,
    nombre: 'Apoderamiento Apud Acta',
    descripcion: 'Poder de representacion electronico ante juzgados',
    portal: Portal.JUSTICIA,
    url: 'https://sedejudicial.justicia.es/-/apoderamiento-apud-acta',
    nombreArchivo: 'Apud_Acta',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: true,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
    notaVerificacion: 'Semi-automatico: navega al Area Privada via Cl@ve, requiere intervencion manual',
  },

  // ── Otros portales ────────────────────────────────────────
  {
    id: TipoDocumento.CERTIFICADO_SEPE,
    nombre: 'Certificado SEPE',
    descripcion: 'Certificado de prestaciones de desempleo del SEPE',
    portal: Portal.SEPE,
    url: 'https://sede.sepe.gob.es/DServiciosPrestanetWEB/TipoAutenticadoAction.do',
    nombreArchivo: 'Certificado_SEPE',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
  },
  {
    id: TipoDocumento.SOLICITUD_CIRBE,
    nombre: 'Solicitud CIRBE',
    descripcion: 'Solicita informe CIRBE al Banco de Espana. Requiere email y fecha de nacimiento. No descarga archivo.',
    portal: Portal.BANCO_ESPANA,
    url: 'https://aps.bde.es/cir_www/cir_wwwias/xml/Arranque.html',
    nombreArchivo: 'Solicitud_CIRBE',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
    notaVerificacion: 'Requiere email + fecha nacimiento (DD/MM/AAAA). Informe disponible en ~15 min.',
  },
  {
    id: TipoDocumento.OBTENCION_CIRBE,
    nombre: 'Obtencion CIRBE',
    descripcion: 'Descarga el informe CIRBE previamente solicitado. Primero usa "Solicitud CIRBE" y espera ~15 min.',
    portal: Portal.BANCO_ESPANA,
    url: 'https://aps.bde.es/cir_www/cir_wwwias/xml/Arranque.html',
    nombreArchivo: 'Informe_CIRBE',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
    notaVerificacion: 'Requiere solicitud previa. Si no hay solicitudes muestra error claro.',
  },

  // ── Hacienda ─────────────────────────────────────────────
  {
    id: TipoDocumento.DEUDAS_HACIENDA,
    nombre: 'Consulta de deudas con Hacienda',
    descripcion: 'Consulta de deudas pendientes con la AEAT (importes y expedientes)',
    portal: Portal.AEAT,
    url: 'https://www1.agenciatributaria.gob.es/wlpl/SRVO-JDIT/ConsultaDdas?faccion=CONS_DDAS',
    nombreArchivo: 'Deudas_Hacienda',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
    notaVerificacion: 'Auth SSL/TLS + printToPdf — implementado desde analisis Findiur',
  },

  // ── Justicia — Registro Civil ───────────────────────────
  {
    id: TipoDocumento.CERTIFICADO_MATRIMONIO,
    nombre: 'Certificado de matrimonio',
    descripcion: 'Certificado literal de matrimonio del Ministerio de Justicia (requiere datos del hecho)',
    portal: Portal.JUSTICIA,
    url: 'https://sede.mjusticia.gob.es/sereci/clave/solicitarCertificadoSolicitudLiteral?idMateria=MAT',
    nombreArchivo: 'Certificado_Matrimonio',
    metodo: MetodoDescarga.DESCARGA_DIRECTA,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: true,
    estadoVerificacion: EstadoVerificacion.VERIFICADO,
    notaVerificacion: 'Semi-auto: Cl@ve + formulario 2 pasos (ano + fecha/provincia/municipio). Usuario rellena datos, will-download captura PDF.',
  },

  // ── Licitaciones ──────────────────────────────────────────
  {
    id: TipoDocumento.PROC_ABIERTOS_GENERAL,
    nombre: 'Procedimientos abiertos (General)',
    descripcion: 'Licitaciones publicas abiertas a nivel nacional',
    portal: Portal.LICITACIONES,
    url: 'https://contrataciondelestado.es/wps/portal/plataforma',
    nombreArchivo: 'Licitaciones_General',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
  },
  {
    id: TipoDocumento.PROC_ABIERTOS_MADRID,
    nombre: 'Procedimientos abiertos (Madrid)',
    descripcion: 'Licitaciones publicas de la Comunidad de Madrid',
    portal: Portal.LICITACIONES,
    url: 'https://contrataciondelestado.es/wps/portal/plataforma',
    nombreArchivo: 'Licitaciones_Madrid',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
  },
  {
    id: TipoDocumento.PROC_ABIERTOS_ANDALUCIA,
    nombre: 'Procedimientos abiertos (Andalucia)',
    descripcion: 'Licitaciones publicas de la Junta de Andalucia',
    portal: Portal.LICITACIONES,
    url: 'https://contrataciondelestado.es/wps/portal/plataforma',
    nombreArchivo: 'Licitaciones_Andalucia',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
  },
  {
    id: TipoDocumento.PROC_ABIERTOS_VALENCIA,
    nombre: 'Procedimientos abiertos (Valencia)',
    descripcion: 'Licitaciones publicas de la Comunidad Valenciana',
    portal: Portal.LICITACIONES,
    url: 'https://contrataciondelestado.es/wps/portal/plataforma',
    nombreArchivo: 'Licitaciones_Valencia',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
  },
  {
    id: TipoDocumento.PROC_ABIERTOS_CATALUNYA,
    nombre: 'Procedimientos abiertos (Catalunya)',
    descripcion: 'Licitaciones publicas de la Generalitat de Catalunya',
    portal: Portal.LICITACIONES,
    url: 'https://contrataciondelestado.es/wps/portal/plataforma',
    nombreArchivo: 'Licitaciones_Catalunya',
    metodo: MetodoDescarga.PRINT_TO_PDF,
    activoPorDefecto: false,
    multiArchivo: false,
    semiAutomatico: false,
    estadoVerificacion: EstadoVerificacion.NO_PROBADO,
  },
]

/** Obtener definicion de un documento por su tipo */
export function obtenerDefinicion(tipo: TipoDocumento): DefinicionDocumento | undefined {
  return CATALOGO_DOCUMENTOS.find((d) => d.id === tipo)
}

/** Documentos activos por defecto */
export function documentosPorDefecto(): TipoDocumento[] {
  return CATALOGO_DOCUMENTOS
    .filter((d) => d.activoPorDefecto)
    .map((d) => d.id)
}
